// Generated by scripts/generate-web-changelog.ts. Do not edit.
export const GENERATED_WEB_CHANGELOG = [
  {
    version: "0.1.0",
    date: "2026-08-26",
    changes: [
      "Added multiplayer Excalidraw canvases with presence, viewport memory, and embedded terminals.",
      "Added persistent pads, machine-backed terminal sessions, and reconnect-safe scene storage.",
      "Added an authenticated self-hosted web application with public-origin verification.",
    ],
  },
] as const;
