export {
  DEFAULT_TERMINAL_HEIGHT,
  DEFAULT_TERMINAL_WIDTH,
  ELEMENTS_KEY,
  LOCAL_ORIGIN,
  REMOTE_ORIGIN,
  REPAIR_ORIGIN,
  SERVER_PLACE_ORIGIN,
  changedElementIds,
  createSceneDoc,
  decodeUpdate,
  elementText,
  elementsMap,
  encodeUpdate,
  nextZIndex,
  patchElement,
  readElement,
  readElements,
  removeElement,
  writeElement,
  type ScenePatch,
} from "./scene-doc.ts";
export * as Y from "yjs";
